SP_ASPNET_1/Controllers/BlogPostController.cs
using SP_ASPNET_1.DbFiles.Operations;
using SP_ASPNET_1.Models;
using SP_ASPNET_1.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Routing;
using System.Threading.Tasks;
using SP_ASPNET_1.BusinessLogic;
using System;


namespace SP_ASPNET_1.Controllers
{
    [RoutePrefix("Blog")]
    public class BlogPostController : Controller
    {
        private readonly BlogPostOperations _blogPostOperations = new BlogPostOperations();
        private readonly LoginOperations _bloglogOperations = new LoginOperations();

        [Route("")]
        [HttpGet]
        public ActionResult Index()
        {
            BlogIndexViewModel result = this._blogPostOperations.GetBlogIndexViewModel();
            ViewBag.Title = "Blog";
            return this.View(result);
        }

        [Route("Detail/{id:int?}")]
        [HttpGet]
        public ActionResult SinglePost(int? id)
        {
            ViewBag.Title = "single post";
            ViewBag.ReturnUrl = Request.UrlReferrer;

            BlogSinglePostViewModel modelView;

            if (id == null)
            {
                modelView = this._blogPostOperations.GetLatestBlogPost();
            }
            else
            {
                modelView = this._blogPostOperations.GetBlogPostByIdFull((int)id);
            }

            return View(modelView);
        }

        [Route("Detail/Random")]
        [HttpGet]
        public ActionResult RandomPost()
        {
            ViewBag.Title = "Random post";

            var viewModel = this._blogPostOperations.GetRandomBlogPost();

            return View(viewModel);
        }

        [Route("LatestPost")]
        [HttpGet]
        public ActionResult LatestPost()
        {
            var viewModel = this._blogPostOperations.GetLatestBlogPost();

            return this.PartialView("~/Views/BlogPost/_BlogPostRecentPartialView.cshtml", viewModel);
        }

        [Route("Create")]
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Route("Create")]
        [Authorize(Roles = "Admin,Author")]
        [HttpPost]
        public ActionResult Create(BlogPost blogPost)
        {
            try
            {
               
                BlogPost blogpostentity = new BlogPost();
                blogpostentity = blogPost;
                blogpostentity.Author = null;

               
                    blogpostentity.AuthorID = (int)(Session["UserID"]);
                
               
                                   
                if (this._blogPostOperations.Create(blogpostentity) > 0)
                {
                    return Json(new {success = true, url = Url.Action("Index", "Home") });
                }
                else
                {
                    return Json(new { failure = true });
                }
            }
            catch
            {
               
                    return View();
            }
        }

        [Route("Edit/{id:int?}")]
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public ActionResult EditBlogPost(int id)
        {
            BlogSinglePostViewModel  blogPost;

            blogPost = this._blogPostOperations.GetBlogPostByIdFull((int)id);

            blogPost.Author = blogPost.BlogPost.Author;
            return View(blogPost);
        }

        [Route("Edit/{id:int}")]
        [Authorize(Roles = "Admin,Author")]
        [HttpPost]
        public ActionResult EditBlogPost(int id, BlogPost blogpost)
        {
            try
            {
                
                    if (this._blogPostOperations.Edit(blogpost) > 0)
                    {
                        return Json(new { success = true, url = Url.Action("Detail", "Blog",new {id=blogpost.BlogPostID })});
                    }
                    else
                    {
                        return Json(new { failure = true });
                    }
                // return View();
            }
           
            catch
            {
                return View();
            }
        }

        [Route("Delete/{id:int}")]
        [Authorize(Roles = "Admin,Author")]
        [HttpGet]
        public ActionResult DeleteBlogPost(int id)
        {
            try
            {


                BlogPost blogPost = this._blogPostOperations.GetBlogPostByIdD((int)id);

                return View(blogPost);
            }
            catch
            {
                return this.HttpNotFound();
            }
        }

        [Route("Delete/{id:int}")]
        [Authorize(Roles = "Admin,Author")]
        [HttpPost]
        public ActionResult DeleteBlogPost(int id,BlogPost blogPost)
        {
            try
            {
                if (this._blogPostOperations.Delete(id) > 0)
                {

                    //CHECK: should return to blogs
                    return Json(new { success = true, url = Url.Action("Index", "Home") });
                }
                else
                {
                    return Json(new { failure = true });
                }
            }
            catch
            {
                return this.HttpNotFound();
            }
        }
      [HttpPost]
        public ActionResult Check(int blogPostId,int blogLike)
        {
            var result = this._blogPostOperations.Updatelikeblog(blogLike, blogPostId);
               
                if (result > 0)
                {
                    return Json(new { success = true });
                }
                else
                {
                    return Json(new {failure = true });
                }
            }          
        }
    }

SP_ASPNET_1/Views/Shared/_Layout.cshtml
@using SP_ASPNET_1.BusinessLogic

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title @(ViewBag.Title != null ? "-" : "") .NET Developer Challenge</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</head>
<body>
  
<header class="header">
<div class="header__navbar">
<img #logo src="~/Content/images/logo.png" /> <span class="spacer"></span>
<nav>
    <ul>
        <li><a href="@Url.Action("Index", "Home")" class="@(@Html.IsActive("Home", "Index"))">HOME</a></li>
        <li>
            <a href="@Url.Action("About", "Home")" class="@(@Html.IsActive("Home", "About"))">ABOUT</a>
            <ul>
                <li><a href="@Url.Action("Product", "Home")" class="@(@Html.IsActive("Home", "Product"))">PRODUCT</a></li>
            </ul>
        </li>
        <li>
            <a href="@Url.Action("Index", "BlogPost")" class="@(@Html.IsActive("BlogPost", "Index"))">BLOG</a>

            <ul style="z-index: 999;">
                <li><a href="@Url.Action("RandomPost", "BlogPost")" class="@(@Html.IsActive("BlogPost", "RandomPost"))">RANDOM POST</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin") || User.IsInRole("Author"))
                    {
                        <li><a href="@Url.Action("Create", "BlogPost")" class="@(@Html.IsActive("Create", "BlogPost"))">CREATE BLOG</a></li>
}
                }
            </ul>
        </li>
        <li><a href="@Url.Action("Contact", "Home")" class="@(@Html.IsActive("Home", "Contact"))">CONTACT</a></li>
        @if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("Admin"))
            {
                <li> <a href="@Url.Action("RoleAssign", "Admin")" class="@(@Html.IsActive("Admin", "RoleAssign"))">ADMIN</a> </li>
             }
            <li><a href="@Url.Action("Logout", "Login")" class="@(@Html.IsActive("Logout", "Login"))">LOGOUT</a></li>
 }
        else
        {
            <li><a href="@Url.Action("Login", "Login")" class="@(@Html.IsActive("Login", "Login"))">LOGIN</a></li>
}
    </ul><p style="text-align:right">@User.Identity.Name @Session["UserName"]</p>

</nav>
</div>

</header>
@RenderBody()
<footer>
<div>
<div class="container">
<div class="social">
<a href="#" class="facebook"></a>
<a href="#" class="googleplus"></a>
<a href="#" class="pinterest"></a> <a href="#" class="twitter"></a>
</div>
<p>© 2020 BBS</p>
</div>
</div>
</footer>
@RenderSection("scripts", required: false)
</body>
</html>

SP_ASPNET_1/Views/Shared/_ShowComments.cshtml
@model IQueryable<SP_ASPNET_1.Models.BlogPostComment>
@using SP_ASPNET_1.Models



@if (Model.Any())
{

    foreach (BlogPostComment comment in Model)
    {
        <div class="row" id="@string.Format("{0}_{1}","CommentsBlock",comment.BlogPostCommentId)" style="width: 100.3%; border-bottom: 1px solid #d2cece; margin-right: -14px; margin-left: -1px;">

            <div class="col-md-4" style="width: 21%;">
                <div class="userProfil" style="margin-left: 9px; margin-top: 12px;">
                    @*<img src="~/Images/@comment.Author.Name" class="img-circle" style="width: 46px; height: 53px; border: 1px solid #bcb8b8;" />*@
                    <a href="#" style="margin-left: 5px; font-weight: bold; font-size: 13px;"> @comment.Author.Name </a>

                </div>
            </div>

            <div class="col-md-7" style="width: 60%;">
                <div class="commentDetails">
                    <p style="margin-top: 27px; font-size: 13px; color: #9c9898;"> @comment.Comments </p>
                    @if ((int)Session["UserId"] == comment.AuthorID)
                    {
                        <a href="#" class="Delete" id="deletecomment" data-id="@comment.BlogPostCommentId" onclick="removeFile(); return false;">Delete</a>
                    <button type="button" id="btn_deletecomment" class="btn btn-default" data-id="@comment.BlogPostCommentId" value="Delete">Delete</button>}
                    @*<div class="@string.Format("{0}_{1}", "ReplayComments", comment.BlogPostCommentId)" style="display:none;">


                            <div class="ReplayCommentInput" style="margin-left: 3%;  margin-bottom: 5px; margin-top: 8px;">
                                <input type="text" id="@string.Format("{0}_{1}", "inputReplay", comment.BlogPostCommentId)" class="form-control" placeholder="Add a Comment ..." style="display: inline;" />
                                <button type="button" class="btn btn-default ReplyAddComment" data-id="@comment.BlogPostCommentId"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span></button>
                            </div>

                        </div>*@

                </div>
            </div>
            <div class="col-md-1" style="width: 19%;">
                <div class="commentDate">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                    <time class="timeago" style="margin-top: 27px; font-size: 13px; color: #9c9898;  margin-left: 4px;" datetime="@comment.DateTime">@comment.DateTime</time>

                </div>
            </div>
        </div>

    }

}
else
{
<div class="row" style="width: 100.3%; border-bottom: 1px solid #d2cece; margin-right: -14px; margin-left: -1px;">
    <div class="commentDetails">
        <div class="col-md-4" style="width: 50%;">
            <p>  No Comments for this Post......</p>

        </div>
        </div>
    </div>
 }

 <script type="text/javascript">
     $(document).ready(function () {
         $("#btn_deletecomment").click(function () {
             var answer = confirm("Are you sure you want to delete this Comment?");
             var commentpostId = $(this).attr('data-id');
             var allCommentsArea = $('<div>').addClass('allComments_' + commentpostId);
             if (answer) {

                 $.ajax({
                     type: 'Post',
                     dataType: 'Json',
                     data: { commentpostId },
                     url: '@Url.Action("DeleteComments", "Comment")',
                     async: true,

                     success: function (result) {
                         $('div[class=CommentsBlock_' + commentpostId + ']').remove();
                         alert("Deleted");
                         $('div[class=CommentsBlock_' + commentpostId + ']').html(result);
                         allCommentsArea.prependTo('#commentsBlock_' + postId);
                         $('#comment_' + id).val("");

                     },
                     failure: function () {
                         alert("Not Deleted");
                     }
                 });
             }

         });
     });
    </script>